/*
 * login action types
 */
export const LOGIN_WITH_FIREBASE = 'LOGIN_WITH_FIREBASE';
export const LOGIN_WITH_FACEBOOK = 'LOGIN_WITH_FACEBOOK';
export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const TYPING_EMAIL = 'TYPING_EMAIL'
export const TYPING_PASSWORD = 'TYPING_PASSWORD'
/**
 * register action types
 */
export const TYPING_USERNAME = 'TYPING_USERNAME';
export const TYPING_REGISTER_EMAIL = 'TYPING_REGISTER_EMAIL';
export const TYPING_REGISTER_PASSWORD = 'TYPING_REGISTER_PASSWORD';
export const TYPING_REGISTER_CONFIRM_PASSWORD = 'TYPING_REGISTER_CONFIRM_PASSWORD';
export const BIRTHDAY_SELECTED = 'BIRTHDAY_SELECTED';
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_CANCELED = 'REGISTER_CANCELED';
export const REGISTERING = 'REGISTERING';
export const REGISTER_WITH_FIREBASE = 'REGISTER_WITH_BASE'

/**
 * control action types
 */
export const GETTING_DATE = 'GETTING_DATE';
export const LOGIN_WITH_FIREBASE_SUCCESSFUL = 'LOGIN_WITH_FIREBASE_SUCCESSFUL'
export const LOGIN_WITH_FIREBASE_FAILURE = 'LOGIN_WITH_FIREBASE_FAILURE'

/**
 * Fetching all team member action
 */
export const REQUEST_FETCH_ALL_TEAM_MEMBER = 'REQUEST_FETCH_ALL_TEAM_MEMBER'
export const FETCH_ALL_TEAM_MENBER_SUCCESSFUL = 'FETCH_ALL_TEAM_MENBER_SUCCESSFUL'
export const FETCH_ALL_TEAM_MEMBER_FAILURE = 'FETCH_ALL_TEAM_MEMBER_FAILURE'

/**
 * has team
 */
export const REQUEST_CHECK_HAS_TEAM = 'REQUEST_CHECK_HAS_TEAM'
export const CHECK_HAS_TEAM_SUCCESSFUL = 'CHECK_HAS_TEAM_SUCCESSFUL'
export const CHECK_HAS_TEAM_FAILURE = 'CHECK_HAS_TEAM_FAILURE'


/**
 * is leader
 */
export const REQUEST_CHECK_IS_LEADER = 'REQUEST_CHECK_IS_LEADER'
export const CHECK_IS_LEADER_SUCCESSFUL = 'CHECK_IS_LEADER_SUCCESSFUL'
export const CHECK_IS_LEADER_FAILURE = 'CHECK_IS_LEADER_FAILURE'

/**
 * exception actions
 */
export const EXCEPTION = 'EXCEPTION'