/*
 * login action types
 */
export const LOGIN_WITH_FIREBASE = 'LOGIN_WITH_FIREBASE';
export const LOGIN_WITH_FACEBOOK = 'LOGIN_WITH_FACEBOOK';
export const LOGIN_WITH_GOOGLE = 'LOGIN_WITH_GOOGLE';
export const TYPING_EMAIL = 'TYPING_EMAIL'
export const TYPING_PASSWORD = 'TYPING_PASSWORD'
/**
 * register action types
 */
export const TYPING_USERNAME = 'TYPING_USERNAME';
export const TYPING_REGISTER_EMAIL = 'TYPING_REGISTER_EMAIL';
export const TYPING_REGISTER_PASSWORD = 'TYPING_REGISTER_PASSWORD';
export const TYPING_REGISTER_CONFIRM_PASSWORD = 'TYPING_REGISTER_CONFIRM_PASSWORD';
export const BIRTHDAY_SELECTED = 'BIRTHDAY_SELECTED';
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const REGISTER_CANCELED = 'REGISTER_CANCELED';
export const REGISTERING = 'REGISTERING';
export const REGISTER_WITH_FIREBASE = 'REGISTER_WITH_BASE'

/**
 * control action types
 */
export const GETTING_DATE = 'GETTING_DATE';
export const LOGIN_WITH_FIREBASE_SUCCESSFUL = 'LOGIN_WITH_FIREBASE_SUCCESSFUL'
